_BASE_: "../Base-BAText.yaml"
MODEL:
  BATEXT:
    POOLER_RESOLUTION: (8,128)
    NUM_CHARS: 100
    TEST_CONFIDENCE_THRESHOLD: 0.65
DATASETS:
  TRAIN: ("ctw1500_word_train",)
  TEST: ("ctw1500_word_test",)
INPUT:
  HFLIP: False
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800, 832, 864, 896)
  MAX_SIZE_TRAIN: 1600
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1024