_BASE_: "Base-MEInst.yaml"
MODEL:
  WEIGHTS: "/mnt/cephfs_new_wj/mlnlp/zhangrufeng/pretrained/detectron2/R-50.pkl"
  RESNETS:
    DEPTH: 50
  MEInst:
    # append for MaskEncoding
    USE_DEFORMABLE: True
    MASK_ON: True
    DIM_MASK: 60
    MASK_SIZE: 28
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  WARMUP_METHOD: "constant"
  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 500
OUTPUT_DIR: "output/MESeg/R_50_1x"